services:
  app:
    image: nextcloud:stable
    restart: unless-stopped
    volumes:
      - ./html:/var/www/html
      - ./data:/var/www/html/data
    environment:
      - MYSQL_HOST=nextcloud-db
      - MYSQL_DATABASE=${NC_DB_NAME:-nextcloud}
      - MYSQL_USER=${NC_DB_USER}
      - MYSQL_PASSWORD=${NC_DB_PASSWORD}
      - NEXTCLOUD_ADMIN_USER=${NC_ADMIN_USER}
      - NEXTCLOUD_ADMIN_PASSWORD=${NC_ADMIN_PASSWORD}
    networks:
      - default
      - dw_inbound_network
    depends_on:
      - db

  db:
    image: mariadb:10.11
    restart: unless-stopped
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${NC_DB_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${NC_DB_PASSWORD}
      - MYSQL_DATABASE=${NC_DB_NAME:-nextcloud}
      - MYSQL_USER=${NC_DB_USER}
    networks:
      - default # Totalmente aislada del proxy exterior

networks:
  dw_inbound_network:
    name: ${DW_GLOBAL_NETWORK:-dw-routing}
    external: true