# Formato: id_interno|Nombre Visual|categoría
nginx_proxy_manager|Nginx Proxy Manager|proxy
wg_easy|WG-Easy|network
nextcloud|Nextcloud|storage
jellyfin|Jellyfin|media
immich|Immich|media
adguard_home|AdGuard Home|network
odoo|Odoo CE|business
vaultwarden|Vaultwarden|security
limesurvey|LimeSurvey|business
fail2ban|Fail2Ban|security
mailserver|Mail Server|network