# Definición de rutas globales del sistema
STACKS_ROOT="/opt/stacks"
DOCKGE_ROOT="/opt/dockge"

# Configuración de red interna de DockerWarrior
DW_NETWORK="dw-routing"

# Puertos asignados por defecto a la infraestructura base
DOCKGE_PORT="5001"
PORTAINER_PORT="9443"