# Control centralizado de tags de imágenes Docker (Producción)
# Actualizar estas variables actualizará las plantillas automáticamente
VERSION_DOCKGE="1.4.2"
VERSION_PORTAINER="2.21.5"
VERSION_NPM="2.12.1"
VERSION_WGEASY="14.1.2"
VERSION_NEXTCLOUD="29.0.2"
VERSION_JELLYFIN="10.9.6"
VERSION_IMMICH="v1.106.1"
VERSION_ADGUARD="v0.107.52"
VERSION_VAULTWARDEN="1.31.0"