services:
  app:
    image: jc21/nginx-proxy-manager:latest
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - 80:80
      - 81:81
      - 443:443
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    networks:
      - default
      - dw_inbound_network              # Sub-red virtual interna del stack para el tráfico entrante
    depends_on:
      - db
  db:
    image: mariadb:10.11
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_MYSQL_NAME}
      MYSQL_USER: ${DB_MYSQL_USER}
      MYSQL_PASSWORD: ${DB_MYSQL_PASSWORD}
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - default                         # La base de datos queda totalmente aislada en la red local por defecto

networks:
  dw_inbound_network:
    name: ${DW_GLOBAL_NETWORK:-dw-routing} # <-- FILOSOFÍA DW-APPSPEC: Dinámico vía .env con fallback seguro
    external: true