services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    env_file:
      - .env
    environment:
      DB_MYSQL_HOST: "db"
      DB_MYSQL_PORT: 3306
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    depends_on:
      - db
    networks:
      - default
      - dw_proxy_network

  db:
    image: 'mariadb:10.11'
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_MYSQL_DATABASE}
      MYSQL_USER: ${DB_MYSQL_USER}
      MYSQL_PASSWORD: ${DB_MYSQL_PASSWORD}
    volumes:
      - ./mysql:/var/lib/mysql

networks:
  dw_proxy_network:
    external: true