# ==============================================================================
# DockerWarrior Application Specification (DW-AppSpec v1.0)
# ==============================================================================
APP_ID="nginx_proxy_manager"
APP_NAME="Nginx Proxy Manager"
CATEGORY="network"
VERSION="2.12.1"

# Redes globales compartidas que deben existir previamente en el motor de Docker
REQUIRED_NETWORKS=(
    "dw_proxy_network"
)